// Code generated by protoc-gen-zig
///! package google.protobuf
const std = @import("std");

const protobuf = @import("protobuf");
const fd = protobuf.fd;

pub const FieldMask = protobuf.wkt.FieldMask;
